server:
  port: 9401

spring:
  application:
    name: oauth2-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/

