server:
  port: 9527


spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: microservicecloud-zuul  #自定义服务名称信息
    prefer-ip-address: true   #访问路径显示ip地址

zuul:
  ignored-services: "*"
  prefix: /atguigu
  routes:
    mydept:
      serviceId: microservicecloud-dept
      path: /mydept/**


info:
  app.name: atguigu-microservicecloud
  company: www.atguigu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}