server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.atguigu.springcloud.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                    #数据库连接池最小维持连接数
      initial-size: 5                #初始化连接数库
      max-total: 5                   #最大连接数
      max-wait-millis: 200          #等待获取连接最大超时时间

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001   #自定义服务名称信息
    prefer-ip-address: true   #访问路径显示ip地址

info:
  app.name: atguigu-microservicecloud
  company: www.atguigu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}