server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002   #euraka服务端实例名称
  client:      #注意和instance是平级的关系
    register-with-eureka: false   #不用注册本身
    fetch-registry: false   #不需要检索服务
    service-url:
       defaultZone: http://eureka7001:7001/eureka/,http://eureka7003:7003/eureka/ #设置与Eureka服务端交互地址

